name: Merge-to-Main
on:
  push:
    branches:
      - main
  # allows you to manually trigger this in GH actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install Packages
        run: npm ci --ignore-scripts

      - name: Build 🔧
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
