name: PR Checks
on:
  pull_request:
    branches:
      - main
  # allows you to manually trigger this in GH actions
  workflow_dispatch:

jobs:
  Test_And_Audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install Packages
        run: npm ci --ignore-scripts

      - name: Audit
        run: npm audit --audit-level=high

      - name: Verify
        run: npm run verify
